package com.projetoacao.lancarAcaoFomento;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class acao implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "ACAO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "ACAO_ID_GENERATOR", sequenceName = "ACAO_ID_SEQ")
	@org.kie.api.definition.type.Label("ID")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Tipo Fomento")
	private java.lang.String tipo_fomento;

	@org.kie.api.definition.type.Label("Linha Fomento")
	private java.lang.String linha_fomento;

	@org.kie.api.definition.type.Label("Número")
	private java.lang.Integer numero;

	@org.kie.api.definition.type.Label("Ano")
	private java.lang.Integer ano;

	@org.kie.api.definition.type.Label("Título")
	private java.lang.String titulo;

	@org.kie.api.definition.type.Label("Sigla")
	private java.lang.String sigla;

	public acao() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getTipo_fomento() {
		return this.tipo_fomento;
	}

	public void setTipo_fomento(java.lang.String tipo_fomento) {
		this.tipo_fomento = tipo_fomento;
	}

	public java.lang.String getLinha_fomento() {
		return this.linha_fomento;
	}

	public void setLinha_fomento(java.lang.String linha_fomento) {
		this.linha_fomento = linha_fomento;
	}

	public java.lang.Integer getNumero() {
		return this.numero;
	}

	public void setNumero(java.lang.Integer numero) {
		this.numero = numero;
	}

	public java.lang.Integer getAno() {
		return this.ano;
	}

	public void setAno(java.lang.Integer ano) {
		this.ano = ano;
	}

	public java.lang.String getTitulo() {
		return this.titulo;
	}

	public void setTitulo(java.lang.String titulo) {
		this.titulo = titulo;
	}

	public java.lang.String getSigla() {
		return this.sigla;
	}

	public void setSigla(java.lang.String sigla) {
		this.sigla = sigla;
	}

	public acao(java.lang.Long id, java.lang.String tipo_fomento,
			java.lang.String linha_fomento, java.lang.Integer numero,
			java.lang.Integer ano, java.lang.String titulo,
			java.lang.String sigla) {
		this.id = id;
		this.tipo_fomento = tipo_fomento;
		this.linha_fomento = linha_fomento;
		this.numero = numero;
		this.ano = ano;
		this.titulo = titulo;
		this.sigla = sigla;
	}

}